routes/web.php
<?php

use App\Http\Controllers\NewsController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\CinemaController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\TimetableController;
use App\Http\Controllers\FilmCardController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\PosterController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\HomePageController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\PageController as AdminPageController;
use App\Http\Controllers\Admin\StockController as AdminStockController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\SessionController;
use App\Http\Controllers\Admin\HallController;
use App\Http\Controllers\Admin\CinemaController as AdminCinemaController;
use App\Http\Controllers\Admin\BannersController;
use App\Http\Controllers\Admin\FilmController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\IndexController;
use App\Http\Controllers\Admin\MailingListController;
use League\CommonMark\Extension\CommonMark\Node\Block\IndentedCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/poster', [PosterController::class, 'index'])->name('poster');
Route::get('/localization/{lang}', [LocalizationController::class, 'index'])->name('localization');
Route::get('/film/{id}', [FilmCardController::class, 'index'])->name('film');
Route::get('/timetable', [TimetableController::class, 'index'])->name('timetable');
Route::get('/booking/{idSession}', [TimetableController::class, 'bookingTicket'])->name('booking');
Route::post('/booking/save', [TimetableController::class, 'saveBooking'])->name('booking.save')->middleware('auth');;
Route::get('/registration', [RegistrationController::class, 'registration'])->name('registration');
Route::post('/user/save', [RegistrationController::class, 'userSave'])->name('userSave');
Route::get('/login', [RegistrationController::class, 'login'])->name('login');
Route::post('/login/auth', [RegistrationController::class, 'auth'])->name('login.auth');
Route::get('/account', [RegistrationController::class, 'account'])->name('account');
Route::put('/account/save', [RegistrationController::class, 'accountSave'])->name('account.save');
Route::get('/logout', [RegistrationController::class, 'logout'])->name('logout');
Route::get('/cinemas', [CinemaController::class, 'index'])->name('cinemas');
Route::get('/cinema/{cinema}', [CinemaController::class, 'show'])->name('cinema.show');
Route::get('/hall/{hall}', [CinemaController::class, 'showHall'])->name('hall.show');
Route::get('/stock', [StockController::class, 'index'])->name('stock');
Route::get('/stock/{stock}', [StockController::class, 'show'])->name('stock.show');
Route::get('/news', [NewsController::class, 'index'])->name('news');
Route::get('/news/{news}', [NewsController::class, 'show'])->name('news.show');
Route::get('/contacts', [PageController::class, 'contacts'])->name('contacts');
Route::get('/mobile-app', [PageController::class, 'mobileApp'])->name('mobile-app');
Route::get('/page/{page}', [PageController::class, 'index'])->name('page');




Route::group(['prefix' => 'admin', 'middleware' => 'isAdmin'], function()
{
    Route::get('/', IndexController::class);
    Route::get('/banners', [BannersController::class, 'index'])->name("banners");
    Route::post('/banners/save/slider/top', [BannersController::class, 'saveSliderTop'])->name("save.slider.top");
    Route::post('/banners/save/slider/news', [BannersController::class, 'saveSliderNews'])->name("save.slider.news");
    Route::post('/banners/save/rotational-speed/top', [BannersController::class, 'saveRotationalSpeedTop'])->name("save.rotational-speed.top");
    Route::post('/banners/save/banner', [BannersController::class, 'saveBanner'])->name("save.banner");
    Route::get('/banners/delete/banner', [BannersController::class, 'deleteBanner'])->name("delete.banner");
    Route::resource('films', FilmController::class);
    Route::resource('films.sessions', SessionController::class)->shallow();
    Route::resource('cinemas', AdminCinemaController::class)->except(['show']);
    Route::resource('cinemas.halls', HallController::class)->shallow();
    Route::resource('news', AdminNewsController::class)->except(['show']);
    Route::resource('stock', AdminStockController::class)->except(['show']);
    Route::resource('pages', AdminPageController::class);
    Route::resource('contacts', ContactController::class)->only(['index', 'store']);
    Route::resource('home-page', HomePageController::class)->only(['index', 'store']);
    Route::resource('users', UserController::class)->except(['show','create', 'store']);
    Route::get('/mailing', [MailingListController::class, 'index'])->name('mailing.index');
    Route::post('/mailing/send', [MailingListController::class, 'send'])->name('mailing.send');
    Route::get('/mailing/getQueueCount', [MailingListController::class, 'getQueueCount'])->name('mailing.getQueueCount');
});

resources/views/admin/pages/contacts.blade.php
@extends('admin.layout')
@section('content')
<div class="container">
    <form action="{{route('contacts.store')}}" method="POST" enctype = "multipart/form-data">
        @csrf
        <div class="row justify-content-center mt-5" id='wrapper'>
            <div class="col-auto" id="btnWrapper">
                <button type="button" class="btn btn-outline-success" id="btn">
                    <img src="{{asset('default-images/plus-lg.svg')}}" width="30" height="30" alt="{{ __('Add image') }}">
                    <label class="mt-1">{{__('Add Cinema')}}</label>
                </button>
            </div>
            <div class="row mb-3 mt-3">
                <div class="col-auto">
                    <label class="col-form-label">{{__('SEO block')}}</label>
                </div>
                <div class="col-9">
                    <div class="row mb-3">
                        <div class="col-auto">
                            <label class="col-form-label">{{__('URL:')}}</label>
                        </div>
                        <div class="col">
                            <input type="text" name="SEOblock[url]" class="form-control" value="{{ isset($SEOBlock->url) ? $SEOBlock->url : '' }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-auto">
                            <label class="col-form-label">{{__('Title:')}}</label>
                        </div>
                        <div class="col">
                            <input type="text" name="SEOblock[title]" class="form-control" value="{{ isset($SEOBlock->title) ? $SEOBlock->title : '' }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-auto">
                            <label class="col-form-label">{{__('Keywords:')}}</label>
                        </div>
                        <div class="col">
                            <input type="text" name="SEOblock[keywords]" class="form-control" value="{{ isset($SEOBlock->keywords) ? $SEOBlock->keywords : '' }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-auto">
                            <label class="col-form-label">{{__('Description:')}}</label>
                        </div>
                        <div class="col">
                            <textarea class="form-control" name="SEOblock[description]" rows="3">{{ isset($SEOBlock->description) ? $SEOBlock->description : '' }}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
            </div>
        </div>
    </form>
</div>


<script>
    index = 0
    $('#btn').on('click', function() {
        $('#btnWrapper').before(
            '<div class="form-control mb-3">'+
                '<div class="row mb-3 mt-3">'+
                    '<div class="col-auto">'+
                       ' <label class="col-form-label">{{__('Cinema name')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<input type="text" name="contacts[' +index+ '][name]" class="form-control">'+
                    '</div>'+
                    '<div class="col-auto ms-auto form-check form-switch form-control-lg">'+
                        '<input class="form-check-input" type="checkbox" name="contacts[' +index+ '][switch]" role="switch">'+
                    '</div>'+
                '</div>'+
                '<div class="row mb-3">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Address')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<textarea class="form-control" name="contacts[' +index+ '][address]" cols="70" rows="10"></textarea>'+
                    '</div>'+
                '</div>'+
                '<div class="row mb-3">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Map coordinates')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<input type="text" name="contacts[' +index+ '][coordinates]" class="form-control">'+
                    '</div>'+
                '</div>'+
                '<div class="row align-items-center mb-3" id="logo">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Logo')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<img class="img-fluid rounded" src="{{asset(config("app.defaultPicture"))}}" style="max-width: 300px; height: 200px" alt="{{ __('logo') }}">'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<div class="row">'+
                            '<div class="col-auto">'+
                                '<input class="form-control" type="file" name="contacts[' +index+ '][logo]" id="logoImg" required>'+
                            '</div>'+
                            '<div class="col-auto">'+
                                '<button class="btn btn-danger" type="button" id="deleteLogo">{{__('Delete')}}</button>'+
                            '</div>'+
                        '</div>'+
                    '</div>'+
                '</div>'+
            '</div>')
            index++;
    })

    @foreach($contacts as $contact)
        console.log('here')
        $('#btnWrapper').before(
            '<div class="form-control mb-3">'+
                '<div class="row mb-3 mt-3">'+
                    '<div class="col-auto">'+
                       ' <label class="col-form-label">{{__('Cinema name')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<input type="text" name="contacts[' +index+ '][name]" class="form-control" value="{{$contact->name}}">'+
                        '<input type="hidden" name="contacts[' +index+ '][idContact]" class="form-control contact" value="{{$contact->idContact}}">'+
                    '</div>'+
                    '<div class="col-auto ms-auto form-check form-switch form-control-lg">'+
                        '<input class="form-check-input" type="checkbox" name="contacts[' +index+ '][switch]" role="switch" {{$contact->switch == 1 ? 'checked' : ''}}>'+
                    '</div>'+
                '</div>'+
                '<div class="row mb-3">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Address')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<textarea class="form-control" name="contacts[' +index+ '][address]" cols="70" rows="10"></textarea>'+
                    '</div>'+
                '</div>'+
                '<div class="row mb-3">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Map coordinates')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<input type="text" name="contacts[' +index+ '][coordinates]" class="form-control" value="{{$contact->coordinates}}">'+
                    '</div>'+
                '</div>'+
                '<div class="row align-items-center mb-3" id="logo">'+
                    '<div class="col-auto">'+
                        '<label class="col-form-label">{{__('Logo')}}</label>'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<img class="img-fluid rounded" src="{{isset($contact->logo) ? asset("$contact->logo") : asset(config("app.defaultPicture"))}}" style="max-width: 300px; height: 200px" alt="{{ __('logo') }}">'+
                    '</div>'+
                    '<div class="col-auto">'+
                        '<div class="row">'+
                            '<div class="col-auto">'+
                                '<input class="form-control" type="file" name="contacts[' +index+ '][logo]" id="logoImg">'+
                            '</div>'+
                            '<div class="col-auto">'+
                                '<button class="btn btn-danger" type="button" id="deleteLogo">{{__('Delete')}}</button>'+
                            '</div>'+
                        '</div>'+
                    '</div>'+
                '</div>'+
            '</div>')
        $(' textarea[name ="contacts[' +index+ '][address]"]').text("{{preg_replace("/[\r\n]+/", "\\n", $contact->address)}}")
        index++;
    @endforeach
    

    $('#wrapper').on('click', "#deleteLogo", function (){
        $(this).closest("#logo").find("img").attr("src","{{asset(config("app.defaultPicture"))}}");
        $(this).closest("#logo").find("#logoImg").val('')
    })
    $('#deleteLogo').on('click', function() {
        $('#filmsForm').append('<input type="hidden" name="deleteLogo">')
        $("#logo").find("img").attr("src","{{asset(config("app.defaultPicture"))}}");
        $('#logoImg').val('').prop('required',true);
    })                   


    $('#wrapper').on('change', "#logoImg", function (event){
        var files = event.target.files, file;
        if (files && files.length > 0) {
            console.log('here')
                    // Получаем загруженный в данный момент файл
            file = files [0]; // Действие проверки размера файла
            if(file.size > 1024 * 1024 * 2) {
                alert ('Размер картинки не может превышать 2 МБ!');
                return false;
            }
            // Получить инструмент URL окна
            var URL = window.URL || window.webkitURL;
            // Генерировать целевой URL через файл, чтобы получить реальный путь
            var imgURL = URL.createObjectURL(file);
            // Используйте attr, чтобы изменить атрибут src img на полученный url
            console.log($(this).closest("#logo").find("img"))
            $(this).closest("#logo").find("img").attr("src",imgURL);
            // Используйте следующее предложение, чтобы освободить сервопривод для этого URL-адреса в памяти, и URL-адрес станет недействительным после запуска
            // URL.revokeObjectURL(imgURL);
        }
    })
</script>
   
@endsection

resources/views/admin/pages/index.blade.php
@extends('admin.layout')
@section('content')
@isset($cinema->halls)
@foreach($cinema->halls as $hall)
    <form action="{{route('halls.destroy', ['hall' => $hall->idHall])}}" method="post" id="delete{{$hall->idHall}}">
        @csrf
        @method('DELETE')
    </form>
    @endforeach
@endisset
<div class="row align-items-center">
    <div class="row text-center m-3 display-4">
        <div class="col-10">{{__('List of pages')}}</div>
        <div class="col-2" id="btnWrapper">
            <a href="{{route('pages.create')}}" class="btn btn-outline-success">
                <img src="{{asset('default-images/plus-lg.svg')}}" width="30" height="30" alt="{{ __('Add image') }}">
                {{__('Create new page')}}
            </a>
        </div>
    </div>
    <table class="table m-e-5">
        <thead>
          <tr>
            <th scope="col">{{__('Name')}}</th>
            <th scope="col">{{__('Created date')}}</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        @foreach($pages as $page)
          <tr>
            <th scope="row">{{$page->name}}</th>
            <td>{{$page->created_at}}</td>
            <td class="col-2">
              @if($page->idPage === 1)
                <a class="btn btn-primary" href="{{route('contacts.index')}}">{{__('edit')}}</a>
              @elseif($page->idPage === 2)
                <a class="btn btn-primary" href="{{route('home-page.index')}}">{{__('edit')}}</a>
              @elseif(in_array($page->idPage, [3,4,5,6,7] ))
                <a class="btn btn-primary" href="{{route('pages.edit', ['page' => $page->idPage])}}">{{__('edit')}}</a>
              @else
                <div class="button-group">
                    <form action="{{route('pages.destroy', ['page' => $page->idPage])}}" method="post">
                      <a class="btn btn-primary" href="{{route('pages.edit', ['page' => $page->idPage])}}">{{__('edit')}}</a>
                      @csrf
                      @method('DELETE')
                      <input class="btn btn-danger" type="submit" value="{{__('delete')}}"/>
                    </form>
                </div>
              @endif
            </td>
          </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/admin/pages/page.blade.php
@extends('admin.layout')
@section('content')

<div class="container mt-3">
    <form action="{{(isset($page) && $page->idPage ? route('pages.update', ['page' => $page->idPage]) : route('pages.store'))}}" method="POST" enctype = "multipart/form-data" id="pageForm">
        @csrf
        @isset($page->idPage)
            @method('PUT')
        @endisset
        <div class="row">
            <div class="col-auto ms-auto form-check form-switch form-control-lg text-end">
                <input class="form-check-input" type="checkbox" name="state" role="switch" {{isset($page->state) && $page->state == 1 ? 'checked' : ''}}>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-auto">
                <label class="col-form-label">{{__('Page name')}}</label>
            </div>
            <div class="col-auto">
                <input type="text" name="name" class="form-control" value="{{isset($page->name) ? $page->name : ''}}">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-auto">
                <label class="col-form-label">{{__('Description')}}</label>
            </div>
            <div class="col-auto">
                <textarea class="form-control" name="description" cols="70" rows="10">{{isset($page->description) ? $page->description : ''}}</textarea>
            </div>
        </div>
        <div class="row align-items-center mb-3" id="logo">
            <div class="col-auto">
                <label class="col-form-label">{{__('Logo')}}</label>
            </div>
            <div class="col-auto">
                <img class="img-fluid rounded" src="{{(isset($page->logo) && $page->logo) ? asset("$page->logo") : asset(config("app.defaultPicture"))}}" style="max-width: 300px; height: 200px" alt="{{ __('logo') }}">
            </div>
            <div class="col-auto">
                <div class="row">
                    <div class="col-auto">
                        <input class="form-control" type="file" name="logo" id="logoImg">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-danger" type="button" id="deleteLogo">{{__('Delete')}}</button>
                    </div>
                </div>
            </div>
        </div>
        <p>{{__('Picture gallery')}}</p>
            <div class="col-auto">
                <p>{{__('Size')}}: 1000x190</p>
            </div>
        <div class="row align-items-center mb-3" id='gallery'>
            <div class="col-3 mt-2" id="btnWrapper">
                <button type="button" class="btn btn-outline-success" id="btn">
                    <img src="{{asset('default-images/plus-lg.svg')}}" width="30" height="30" alt="{{ __('Add image') }}">
                </button>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-auto">
                <label class="col-form-label">{{__('SEO block')}}</label>
            </div>
            <div class="col-9">
                <div class="row mb-3">
                    <div class="col-auto">
                        <label class="col-form-label">{{__('URL:')}}</label>
                    </div>
                    <div class="col">
                        <input type="text" name="SEOblock[url]" class="form-control" value="{{ isset($page->SEOBlock->url) ? $page->SEOBlock->url : '' }}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-auto">
                        <label class="col-form-label">{{__('Title:')}}</label>
                    </div>
                    <div class="col">
                        <input type="text" name="SEOblock[title]" class="form-control" value="{{ isset($page->SEOBlock->title) ? $page->SEOBlock->title : '' }}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-auto">
                        <label class="col-form-label">{{__('Keywords:')}}</label>
                    </div>
                    <div class="col">
                        <input type="text" name="SEOblock[keywords]" class="form-control" value="{{ isset($page->SEOBlock->keywords) ? $page->SEOBlock->keywords : '' }}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-auto">
                        <label class="col-form-label">{{__('Description:')}}</label>
                    </div>
                    <div class="col">
                        <textarea class="form-control" name="SEOblock[description]" rows="3">{{ isset($page->SEOBlock->description) ? $page->SEOBlock->description : '' }}</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
            </div>
        </form>
        </div>
</div>
<script>
    $('#deleteLogo').on('click', function() {
        $('#pageForm').append('<input type="hidden" name="deleteLogo">')
        $("#logo").find("img").attr("src","{{asset(config("app.defaultPicture"))}}");
        $('#logoImg').val('')
    })
    index = 0;
    $('#btn').on('click', function() {
        $('#btnWrapper').before('<div class="col-auto text-center mt-5" style="position: relative; max-width: 337px;">'+
                    '<img src="{{asset(config("app.defaultPicture"))}}" alt="{{__('Image')}}" style="max-width: 100%; height: 200px" class="img-fluid">'+
                    '<input type="hidden" name="slides['+index+'][onDelete]" value="false" id="onDelete">'+
                    '<input type="file" class="form-control mt-1" name="slides['+index+'][img]" required>'+
                    '<button type="button" class="btn btn-circle" style="position: absolute; top: -20px; right: 0px" id="delete">'+
                        '<img src="{{asset('default-images/x-circle.svg')}}" alt="x" width="20" height="20">'+
                    '</button>'+
                '</div>');
            index++;
    })
    @isset($page)
        @foreach ($page->pictures as $slide)
            $('#btnWrapper').before('<div class="col-auto text-center mt-5" style="position: relative; max-width: 337px;">'+
                '<input type="hidden" name="slides['+index+'][id]" value={{$slide->idPicture}}>'+
                '<img src="{{(isset($slide->img) && $slide->img) ? asset("$slide->img") : asset(config("app.defaultPicture"))}}" alt="{{__('Image')}}" style="max-width: 100%; height: 200px" class="img-fluid">'+
                '<input type="hidden" name="slides['+index+'][onDelete]" value="false" id="onDelete">'+
                '<input type="file" class="form-control mt-1" name="slides['+index+'][img]">'+
                '<button type="button" class="btn btn-circle" style="position: absolute; top: -20px; right: 0px" id="delete">'+
                    '<img src="{{asset('default-images/x-circle.svg')}}" alt="x" width="20" height="20">'+
                '</button>'+
            '</div>');
            index++;
        @endforeach
    @endisset
    $('#gallery').on('click', "#delete", function (){
                $(this).parent().children("#onDelete").attr('value', 'true')
                $(this).parent().attr('style','display: none;')
    });

    $('#logoImg').on('change', function(event) {
        var files = event.target.files, file;
        if (files && files.length > 0) {
                    // Получаем загруженный в данный момент файл
            file = files [0]; // Действие проверки размера файла
            if(file.size > 1024 * 1024 * 2) {
                alert ('Размер картинки не может превышать 2 МБ!');
                return false;
            }
            // Получить инструмент URL окна
            var URL = window.URL || window.webkitURL;
            // Генерировать целевой URL через файл, чтобы получить реальный путь
            var imgURL = URL.createObjectURL(file);
            // Используйте attr, чтобы изменить атрибут src img на полученный url
            console.log($(this).closest("#logo").find("img"))
            $(this).closest("#logo").find("img").attr("src",imgURL);
            // Используйте следующее предложение, чтобы освободить сервопривод для этого URL-адреса в памяти, и URL-адрес станет недействительным после запуска
            // URL.revokeObjectURL(imgURL);
            $("input[name = 'deleteLogo']").remove()
        }
    })

    $('#gallery').on('change','[type="file"]',function(event){
        var files = event.target.files, file;
        if (files && files.length > 0) {
                    // Получаем загруженный в данный момент файл
            file = files [0]; // Действие проверки размера файла
            if(file.size > 1024 * 1024 * 2) {
                alert ('Размер картинки не может превышать 2 МБ!');
                return false;
            }
            // Получить инструмент URL окна
            var URL = window.URL || window.webkitURL;
            // Генерировать целевой URL через файл, чтобы получить реальный путь
            var imgURL = URL.createObjectURL(file);
            // Используйте attr, чтобы изменить атрибут src img на полученный url
            $(this).parent().children('img').attr("src",imgURL);
            // Используйте следующее предложение, чтобы освободить сервопривод для этого URL-адреса в памяти, и URL-адрес станет недействительным после запуска
            // URL.revokeObjectURL(imgURL);
        }
    })
    
</script>
<style>
    /* CSS */
    .btn-circle {
        width: 28px;
        height: 28px;
        border-radius: 14px;
        text-align: center;
        padding-left: 0;
        padding-right: 0;
        font-size: 10px;
        background-color: white;
    }
    </style>
@endsection